version: '3.3'

networks:
  logs:
    driver: overlay
    attachable: true

services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - /data/elasticsearch1:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch1
      - cluster.name=logs-mojix-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024M -Xmx1024M"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - logs
    deploy:
      #endpoint_mode: dnsrr
      replicas: 1
      # resources:
      #   limits:
      #     memory: 3g
      # placement:
      #   constraints:
      #     - node.labels.host == ##HOST_LABEL

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - /data/elasticsearch2:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch2
      - cluster.name=logs-mojix-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024M -Xmx1024M"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    ports:
      - 9201:9200
    networks:
      - logs
    deploy:
      #endpoint_mode: dnsrr
      replicas: 1

  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - /data/elasticsearch3:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch3
      - cluster.name=logs-mojix-cluster
      - cluster.initial_master_nodes=elasticsearch1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024M -Xmx1024M"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=0.0.0.0
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    ports:
      - 9202:9200
    networks:
      - logs
    deploy:
      #endpoint_mode: dnsrr
      replicas: 1
