version: '3.3'

networks:
  iot:
    driver: overlay
    attachable: true

configs:
  filebeat-config:
    file: ./filebeat-config.yml

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.4.0
    user: root
    configs:
      - source: filebeat-config
        target: /usr/share/filebeat/filebeat.yml
    networks:
      - iot
    volumes:
      - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
